name: bloom_lints
description: The Bloom Technologies linter for Flutter
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.3
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.3
