name: bloom_lints
description: A recommended set of linter rules by Bloom for Flutter and Dart apps, packages, and plugins to encourage good coding practices.
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
